{{- if and .Values.podDisruptionBudget.enabled (or (and .Values.autoscaling.enabled (gt (int .Values.autoscaling.minReplicas) 1)) (gt (int .Values.replicas) 1)) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "harness-delegate-ng.fullname" . }}
  labels:
    {{- include "harness-delegate-ng.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "harness-delegate-ng.selectorLabels" . | nindent 6 }}
{{- end }}
