name: Helm check, lint and push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'push' && github.run_number || github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  helm:
    name: Helm
    runs-on: ubuntu-24.04
    env:
      CHART_DIR: harness-delegate-ng
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Chart name
        working-directory: ${{ env.CHART_DIR }}
        run: echo "CHART_NAME=$(yq .name Chart.yaml)" >> $GITHUB_ENV

      - name: Get Chart version
        working-directory: ${{ env.CHART_DIR }}
        run: echo "CHART_VERSION=$(yq .version Chart.yaml)" >> $GITHUB_ENV

      - name: Helm package
        working-directory: ${{ env.CHART_DIR }}
        run: helm package ${{ env.CHART_NAME }}

      - name: Helm login
        #if: ${{ github.event_name == 'push' }}
        run: |
          helm registry login \
            ${{ vars.HARNESS_HELM_BASE_URL }} \
            -u ${{ vars.HARNESS_HELM_USER }} \
            -p ${{ secrets.HARNESS_HELM_TOKEN }}

      - name: Helm push
        if: ${{ github.event_name == 'push' }}
        working-directory: ${{ env.CHART_DIR }}
        run: helm push ${{ env.CHART_NAME }}-${{ env.CHART_VERSION }}.tgz ${{ vars.HARNESS_HELM_URL }}
